---
title: "412_ComplicateHousing"
author: "DavidSun"
date: "12/2/2021"
output: pdf_document
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(corrplot)
library(ggplot2)
library(dplyr)
library(glmnet)
library(car)
library(MASS)
library(caret) 
library(ggcorrplot)

# rmse rsquare rss function 
rmse_r2_rss <- function(y, predict, df) {
  RSS <- sum((predict - y)^2)
  TSS <- sum((y - mean(y))^2)
  #R_square <- 1 - RSS / SST
  RMSE = sqrt(RSS/nrow(df))
  n=nrow(df)
  p=ncol(df)-1
  R_square = 1 - (RSS/(n - p))/(TSS/(n - 1)) #adjusted R 2
  # Model performance metrics
data.frame(
  RMSE = round(RMSE,5),
  Rsquare = round(R_square,5)
)
}
```

```{r functions , include=FALSE}
corr_simple <- function(data=df,sig=0.5){
  #convert data to numeric in order to run correlations
  #convert to factor first to keep the integrity of the data - each value will become a number rather than turn into NA
  df_cor <- data %>% mutate_if(is.character, as.factor)
  df_cor <- df_cor %>% mutate_if(is.factor, as.numeric)
  #run a correlation and drop the insignificant ones
  corr <- cor(df_cor)
  #prepare to drop duplicates and correlations of 1     
  corr[lower.tri(corr,diag=TRUE)] <- NA 
  #drop perfect correlations
  corr[corr == 1] <- NA 
  #turn into a 3-column table
  corr <- as.data.frame(as.table(corr))
  #remove the NA values from above 
  corr <- na.omit(corr) 
  #select significant values  
  corr <- subset(corr, abs(Freq) > sig) 
  #sort by highest correlation
  corr <- corr[order(-abs(corr$Freq)),] 
  #print table
  print(corr)
  #turn corr back into matrix in order to plot with corrplot
  mtx_corr <- reshape2::acast(corr, Var1~Var2, value.var="Freq")
  
  #plot correlations visually
  corrplot(mtx_corr, is.corr=FALSE, tl.col="black", na.label=" ",main = paste("Corr Plot Variables > ", sig))
}

rmse <- function(y_hat, y){round(sqrt(mean((y_hat - y)^2)),3)}


```

## R Markdown


```{r }
df_raw<- read.csv('train_edit.csv')
dim(df_raw) 

df<- df_raw[,-1] # remove ID column
head(df,5)
```

```{r}
#summary(df)
sum(is.na(df))
```
```{r}
#replace NA with median in Lot Front Age
df$LotFrontage[is.na(df$LotFrontage)] <- median(df$LotFrontage, na.rm=TRUE)
# remove Na's in MasVnrArea
df1 <-na.omit(df)
sum(is.na(df1))


head(df1)

```

```{r}
df_corr<-cor(df1)

#corrplot(df_corr, method = "circle")
#ggcorrplot(df_corr)

corr_simple(df1) # anything greater than 0.50
```

```{r}

df2 <- subset(df1, select = -c(GarageCars,HouseStyle, BedroomAbvGr,TotRmsAbvGrd,OverallQual, X2ndFlrSF,X1stFlrSF,BsmtFullBath, FullBath,BsmtFinSF1, BsmtFinSF2, BsmtUnfSF  ) )
head(df2)

```


```{r}
corr_simple(df2,.4)
```

Price<=550k set up
```{r}
df3 = subset(df2, SalePrice <= 550000 )
boxplot(df3$SalePrice)
```
Central Air Clean
```{r}
df3$CentralAir[df3$CentralAir =="Y"] <- as.integer(1)
df3$CentralAir[df3$CentralAir =="N"] <- as.integer(0)
```

#EDA
```{r}
corr_simple(df3,sig = 0.4)
```

Sales Price 130k - 210k
```{r}
qplot(df3$SalePrice,xlab = 'Sales Price',main = 'Sales Price Hist',col ='red',bins = 15) # price
quantile(df3$SalePrice, 0.25)
quantile(df3$SalePrice, 0.75)
```


#models

##Train/Test Seperation

```{r}
set.seed(412)
dt = sort(sample(nrow(df3), nrow(df3)*.8))  #80% as train, 20% as test

#train
df_tr <- df3[dt,] #remove state
x_tr <- data.matrix(df_tr[,-c(29)])
y_tr <-df_tr[,c(29)]

#test
df_ts <-  df3[-dt,]
x_ts <-data.matrix(df_ts[,-c(29)])
y_ts <-df_ts[,c(29)]

```


```{r lm}
# Linear Model
lm_housing <- lm(SalePrice ~ ., data=df_tr)
plot(lm_housing)
summary(lm_housing)

# VIF
car::vif(lm_housing)
df
rmse_r2_rss(df_tr$SalePrice,predict(lm_housing,df_tr),df_tr)

rmse_r2_rss(df_ts$SalePrice,predict(lm_housing,df_ts),df_ts)
```

##Linear Regression (Harrison)
```{r}
set.seed(412)
lm_housing2<-step(lm_housing,trace = FALSE)
lm_housing2$coefficients

plot(lm_housing2)
summary(lm_housing2)

# VIF
car::vif(lm_housing2)

#train and test

df_tr1 <- subset(df_tr, select = c( MSSubClass, LotFrontage, LotArea,LandSlope , OverallCond,YearBuilt,YearRemodAdd,    MasVnrArea,TotalBsmtSF, CentralAir, GrLivArea, BsmtHalfBath, KitchenAbvGr, Fireplaces, GarageArea, WoodDeckSF,EnclosedPorch,ScreenPorch, PoolArea,MoSold,SalePrice ) )
df_ts1 <- subset(df_ts, select = c( MSSubClass, LotFrontage,LotArea, LandSlope , OverallCond,YearBuilt,YearRemodAdd,    MasVnrArea,TotalBsmtSF, CentralAir, GrLivArea, BsmtHalfBath, KitchenAbvGr, Fireplaces, GarageArea, WoodDeckSF,EnclosedPorch,ScreenPorch, PoolArea,MoSold,SalePrice ) )


rmse_r2_rss(df_tr1$SalePrice,predict(lm_housing2,df_tr1),df_tr1)
rmse_r2_rss(df_ts1$SalePrice,predict(lm_housing2,df_ts1),df_ts1)


```
###Ridge 
```{r}
set.seed(412)
numeric_features <- as.matrix(df_tr[, -c(29)])

lambdas_to_try <- seq(0, 2, by = 0.001)
ridge_housing_cv <- cv.glmnet(x_tr, y_tr, lambda = lambdas_to_try, standardize = TRUE, nfolds = 10)
min_lambda_ridcv <- ridge_housing_cv$lambda.min
ridge_housing <- glmnet(x_tr, y_tr, alpha = 0, lambda = ridge_housing_cv$lambda.min, standardize = TRUE)


predictions<- predict(ridge_housing, s = min_lambda_ridcv, newx = x_tr)
rmse_r2_rss(y_tr,predictions,x_tr)

predictions<- predict(ridge_housing, s = min_lambda_ridcv, newx = x_ts)
rmse_r2_rss(y_ts,predictions,x_ts)
plot(ridge_housing_cv$glmnet.fit,xvar = "lambda", label = T, main ="ridge_housing_cv$glmnet.fit")
```
##PCA
##PCR (David)
```{r, warning= FALSE}

library(pls)
set.seed(412)

pcr_m <-prcomp(x_tr) 

plot(pcr_m$sdev[1:10],type="l", ylab="SD of PC", xlab="PC number")

pcrmod_cv <- pcr(SalePrice ~ MSSubClass+LotFrontage+LotArea+LotShape+LandSlope+OverallCond+YearBuilt+YearRemodAdd+MasVnrArea+TotalBsmtSF+CentralAir+LowQualFinSF+GrLivArea+BsmtHalfBath+HalfBath+KitchenAbvGr+Fireplaces+GarageArea+PavedDrive+WoodDeckSF+OpenPorchSF+EnclosedPorch+X3SsnPorch+ScreenPorch+PoolArea+MiscVal+MoSold+YrSold, data=df_tr,validation = "CV", scale = TRUE, ncomp =28,segments = 10)
summary(pcrmod_cv)


pcrmse_2_cv <- RMSEP(pcrmod_cv, estimate="CV")
min1<-which.min(pcrmse_2_cv$val)-1 # -1 for intercept
min1




predictions<- predict(pcrmod_cv, df_tr, ncomp = min1)
rmse_r2_rss(y_tr, predictions, x_tr)

predictions<- predict(pcrmod_cv, df_ts, ncomp = min1)
rmse_r2_rss(y_ts, predictions, x_ts)


##########################################################################
#AIC model
pcrmod_cv2 <- pcr(SalePrice ~ MSSubClass+ LotFrontage+ LotArea+LandSlope + OverallCond+YearBuilt+YearRemodAdd+    MasVnrArea+TotalBsmtSF+ CentralAir+ GrLivArea+ BsmtHalfBath+ KitchenAbvGr+ Fireplaces+ GarageArea+ WoodDeckSF+EnclosedPorch+ScreenPorch+ PoolArea+MoSold, data=df_tr,validation = "CV", scale = TRUE, ncomp =20,segments = 10)
summary(pcrmod_cv2)

pcrmse_2_cv2 <- RMSEP(pcrmod_cv2, estimate="CV")
min2<-which.min(pcrmse_2_cv2$val)-1 # -1 for intercept
min2
 
predictions<- predict(pcrmod_cv2, df_tr, ncomp = min2)
rmse_r2_rss(y_tr, predictions, x_tr)

predictions<- predict(pcrmod_cv2, df_ts, ncomp = min2)
rmse_r2_rss(y_ts, predictions, x_ts)
####
library(qpcR)
#round(PRESS(pcrmod_cv)$P.square,3) #.988
#round(PRESS(pcrmod_cv2)$P.square,3) #.983

```

## Polynomial Regression (David )
```{r}
#poly 3
poly_model2 <- lm(df_tr$SalePrice~polym(LotArea, YearBuilt,YearRemodAdd, MasVnrArea, GrLivArea,degree=3,raw=TRUE),data=df_tr)

rmse_r2_rss(df_tr$SalePrice,predict(poly_model2,df_tr),df_tr)
rmse_r2_rss(df_ts$SalePrice,predict(poly_model2,df_ts),df_ts)
#############################################################
#poly 2
poly_model3 <- lm(df_tr$SalePrice~polym(LotArea, YearBuilt,YearRemodAdd, MasVnrArea, GrLivArea,degree=2,raw=TRUE),data=df_tr)

rmse_r2_rss(df_tr$SalePrice,predict(poly_model3,df_tr),df_tr)
rmse_r2_rss(df_ts$SalePrice,predict(poly_model3,df_ts),df_ts)



```
```{r}

```


